name: Python CI

defaults:
  run:
    shell: bash -ieo pipefail {0}

on: 
  push:
    branches: 
      - master
      - dev
  pull_request: 
    branches: 
      - master
      - dev

jobs:
  build_dep:
    uses: ./.github/workflows/build_dep.yml

  test_pushing:
    needs: [build_dep]
    runs-on: ubuntu-20.04
    steps:
      - name: check dep
        run: |
          pip3 freeze
      
        
      #--- pull git repo---
      - name: Checkout repo
        uses: actions/checkout@v3

      #--- load requirements cache ---
      - name: load requ
        id: req-load
        uses: actions/cache/restore@v3
        with: 
          path: ~/.cache/pip
          key: cac
      
      #---- run tests ---
      - name: Run Pytest
        run: |
          pip3 freeze
          python3 -m pytest -v tests
          

