name: Caching Dependencies

on: 
  workflow_call:
    inputs:
      py:
        description: build ros
        type: boolean
        default: true
        required: false

   
jobs:
  build_and_cache_py:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: load requirements
        id: load-req
        uses: actions/cache@v4
        with:
          path: ~/.cache/req
          key: req
      -  if: ${{ steps.load-req.outputs.cache-hit != 'true'}} 
         name: install requirements
         run: |
           python3 -m pip install --upgrade pip  
           pip3 install -r requirements.txt
           pip3 install --upgrade numpy
      -  if: ${{steps.load-req.outputs.cache-hit != 'true'}}
         name: cache requirements
         id: cache-req
         uses: actions/cache/save@v3
         with:
            path: ~/.cache/req
            key: req
      - if: ${{ steps.load-req.outputs.cache-hit == 'true'}}
        name: success_caching
        id: success-caching
        run: |
          echo "Caching Successful"


 