name: Python CI

on: 
  push:
    branches: 
      - master
      - dev
  pull_request: 
    branches: 
      - master
      - dev

jobs:
  build_dep:
    uses: ./.github/workflows/build_dep.yml
  test_pushing:
    needs: [build_dep]
    runs-on: ubuntu-20.04
    steps:
      #--- load requirements cache ---
      - name: load req
        id: req-load
        uses: actions/cache@v2
        with: 
          path: ~/.cache/pip
          key: req
        
      #--- pull git repo---
      - name: Checkout repo
        uses: actions/checkout@v2
      
      #---- run tests ---
      - name: Run Pytest
        run: |
          pytest --version
          pytest -v tests
          

