name: Python CI

on: 
  push:
    branches: 
      - master
      - dev
  pull_request: 
    branches: 
      - master
      - dev

jobs:
  test_pushing:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
      
    - name: install requirements
      run: |
        sudo pip3 install -r requirements.txt
    - name: upgrade numpy
      run: |
        sudo pip3 install --upgrade numpy
    - name: Run Pytest
      run: |
        pytest -v tests

